# Generated by Django 3.0 on 2020-01-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200109_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='date_joined',
            new_name='date_rated',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='group',
            new_name='movie',
        ),
    ]
