# Generated by Django 3.0 on 2020-01-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200112_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=30, max_digits=50)),
                ('movie_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_from', to='content.Movie')),
                ('movie_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_to', to='content.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='similarity',
            field=models.ManyToManyField(through='content.Similarity', to='content.Movie'),
        ),
    ]
